### ISSUE TITLE
[Bug]: "400 Bad Request" for hashtags with special letters

### ISSUE THREAD

**Issue by LukaszH77** [GeopJr/Tuba#246]
### Describe the bug

Tuba shows error while searching for hashtags with special letters. 

I found it while searching for Polish words and checked it's the same for German umlauts.

### Steps To Reproduce

1. Open Search
2. Select Hashtags
3. Enter a hashtag with a special letter
4. Tuba shows "Bad Request"

### Logs and/or Screenshots

```
Tuba-Message: 09:59:16.140: Streams.vala:68: Opening stream: https://mastodon.social/api/v1/streaming/?stream=hashtag&tag=Ry%C5%BCowa%C5%9Aroda
Tuba-Message: 09:59:16.140: Streams.vala:94: Closing: https://mastodon.social/api/v1/streaming/?stream=hashtag&tag=Ry%C5%BCowa%C5%9Aroda
Tuba-Message: 09:59:16.140: Streams.vala:68: Opening stream: https://mastodon.social/api/v1/streaming/?stream=hashtag&tag=Ry%C5%BCowa%C5%9Aroda
Tuba-Message: 09:59:16.140: Network.vala:34: GET: https://mastodon.social/api/v1/tags/RyżowaŚroda
Tuba-Message: 09:59:16.325: Network.vala:34: GET: https://mastodon.social/api/v1/timelines/tag/RyżowaŚroda?limit=20

(dev.geopjr.Tuba:2): Tuba-CRITICAL **: 09:59:16.696: Network.vala:51: Request "https://mastodon.social/api/v1/tags/RyżowaŚroda" failed: 400 Bad Request
```
![Zrzut ekranu z 2023-05-13 10-02-38](https://github.com/GeopJr/Tuba/assets/121253127/9b3cbc16-6b29-4136-985e-fd97ec8ade65)

### Instance Backend

Mastodon

### Operating System

openSUSE Tumbleweed

### Package

Compiled manually

### Troubleshooting information

os: GNOME 44 (Flatpak runtime)
prefix: /app
flatpak: true
version: main-aa17cb3 (development)
gtk: 4.10.3 (4.10.3)
libadwaita: 1.3.2 (1.3.2)
libsoup: 3.4.1 (3.4.1)
libgtksourceview: 5.8.0 (5.8.0)

**Comment by LukaszH77** [comment]
I don't know how useful it can be, but I forgot to add that the official Mastodon client treats these special letters the same as the versions without diacritics, i.e. ó = o, ł = l, ś = s and so on. 

And it shows the same results when searching for both versions, i.e. when searching for #RyżowaŚroda and #RyzowaSroda it will show the same posts.

**Comment by GeopJr** [comment]
It should be fixed as of #248!

(btw heads up: My instance seems to have limited mastodon.social after the crypto bot spam. If you have dmed me recently, I probably haven't received it. I should open a matrix room for tube :sweat_smile:)

**Comment by LukaszH77** [comment]
Unfortunately, it doesn't work for me. I still get "An error occurred. Bad request" message and no posts. But this time there's no "400 Bad Request" in the log.

```
(dev.geopjr.Tuba:2): GLib-GObject-CRITICAL **: 09:08:20.140: ../gobject/gsignal.c:3669: signal name 'open' is invalid for instance '0x55844d8d1f10' of type 'AdwActionRow'
Tuba-Message: 09:08:20.142: Streams.vala:68: Opening stream: https://mastodon.social/api/v1/streaming/?stream=hashtag&tag=Ry%C5%BCowa%C5%9Aroda
Tuba-Message: 09:08:20.142: Streams.vala:94: Closing: https://mastodon.social/api/v1/streaming/?stream=hashtag&tag=Ry%C5%BCowa%C5%9Aroda
Tuba-Message: 09:08:20.142: Streams.vala:68: Opening stream: https://mastodon.social/api/v1/streaming/?stream=hashtag&tag=Ry%C5%BCowa%C5%9Aroda
Tuba-Message: 09:08:20.253: Network.vala:34: GET: https://mastodon.social/api/v1/timelines/tag/Ry?owa?roda?limit=20
```

Matrix room is a very good idea :)

**Comment by GeopJr** [comment]
Could you give #250 a try when it's done?

This happens when you click a tag - not on search, right?

**Comment by LukaszH77** [comment]
I will. And yes, I can search for a tag and get correct results just fine. The error appears after clicking a tag.

**Comment by LukaszH77** [comment]
I tried version fix/hashtag/encode-tag-1e88c4d and it's the same error :( 

But hey, at least I learned how to checkout and build a branch :)

**Comment by GeopJr** [comment]
> I tried version fix/hashtag/encode-tag-1e88c4d and it's the same error :(

(if it does not contain private info) could you share the post you click the hashtag on? On the previous logs you sent, it looks like it replaced the accented letters with question marks (`Ry?owa?roda`) so I want to check if it's an instance issue or similar

FWIW, from mastodon.online it seems to work (extremely laggy video)

[Screencast from 2023-05-14 13-22-13.webm](https://github.com/GeopJr/Tuba/assets/18014039/bf2e953d-27c1-4b15-a8c2-9cca8faee8cb)

> But hey, at least I learned how to checkout and build a branch :)

Great! I didn't mean to put you through that 🙇 I mostly meant the package the CI built

**Comment by LukaszH77** [comment]
I think you may be right, it does look like an instance issue! 

[RecApp-2023-05-15-07:07:28.webm](https://github.com/GeopJr/Tuba/assets/121253127/d03529ee-c021-4c0c-b470-93aa309c3a59)

The first account I'm using in this clip is @mastodon.social, the second one is @pol.social.

**Comment by GeopJr** [comment]
I'm positive that it's now fixed for good!

**Comment by LukaszH77** [comment]
It is! Thank you so much!

**Comment by GeopJr** [comment]
Matrix room: https://matrix.to/#/#tuba:gnome.org
